language: python

python:
    - "2.7"

before_install:
    - cd apartment_gis
    - cp apartment_gis/settings.py.local apartment_gis/settings.py

install:
    - pip install -r configs/requirements.txt

    - psql -c "create user admin password '123';"
    - psql -c "alter user admin superuser;"
    - psql -c "create database test_gis;" -U postgres
    - psql -c "create extension postgis;" -U postgres -d test_gis
    - psql -c "create extension postgis_topology;" -U postgres -d test_gis

before_script:
    - python manage.py syncdb --noinput

script:
    - python manage.py test
