language: python

python:
    - "2.7"

install:
    - pip install -r apartment_gis/configs/requirements.txt

before_script:
    - ln -s apartment_gis/apartment_gis/settings.py.production apartment_gis/apartment_gis/settings.py
    - python apartment_gis/manage.py syncdb --noinput

script:
    - python apartment_gis/manage.py test
